// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzI4DfyYYIntUfv2UpglOJS32tqE7LynY',
    appId: '1:788141476838:web:2e41596b145bd612292427',
    messagingSenderId: '788141476838',
    projectId: 'flutterwavepayment-74b47',
    authDomain: 'flutterwavepayment-74b47.firebaseapp.com',
    storageBucket: 'flutterwavepayment-74b47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBflohSBpBqzhzC5Sdq13q8pQLrYP5MPo4',
    appId: '1:788141476838:android:00603d7988fabc1c292427',
    messagingSenderId: '788141476838',
    projectId: 'flutterwavepayment-74b47',
    storageBucket: 'flutterwavepayment-74b47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPkcW4AlUR4xaDpa2OWazLr_KVjHxygWs',
    appId: '1:788141476838:ios:772a076d8db1ae6d292427',
    messagingSenderId: '788141476838',
    projectId: 'flutterwavepayment-74b47',
    storageBucket: 'flutterwavepayment-74b47.appspot.com',
    iosClientId: '788141476838-l97vh542or0f5e2pbhgakjkk6gto5f3o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterwavepayment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPkcW4AlUR4xaDpa2OWazLr_KVjHxygWs',
    appId: '1:788141476838:ios:8172b98e4946e238292427',
    messagingSenderId: '788141476838',
    projectId: 'flutterwavepayment-74b47',
    storageBucket: 'flutterwavepayment-74b47.appspot.com',
    iosClientId: '788141476838-mgvsruh2bbo7fv0qdjerh009psnbvo3d.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterwavepayment.RunnerTests',
  );
}
